### ISSUE TITLE
ImportError: cannot import name 'CoILAgent'

### ISSUE THREAD

**Issue by wangchangquan** [autonomousvision/data_aggregation#2]
miss __init__.py in dirve cause the problem.  add the file from coiltraine solve it.

pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "multi_gpu_collection.py", line 10, in <module>
    from collect import collect
  File "/home/wangchangquan/data_aggregation/collect.py", line 29, in <module>
    from coil_core import validate_single_model
  File "/home/wangchangquan/data_aggregation/coil_core/__init__.py", line 2, in <module>
    from .executer import execute_train, execute_validation, execute_drive, folder_execute
  File "/home/wangchangquan/data_aggregation/coil_core/executer.py", line 11, in <module>
    from . import train, validate, run_drive
  File "/home/wangchangquan/data_aggregation/coil_core/run_drive.py", line 19, in <module>
    from drive import CoILAgent
ImportError: cannot import name 'CoILAgent'

**Comment by ap229997** [comment]
Thanks for pointing it out. It is fixed now.
